import type { Metadata } from "next";
import CssBaseline from "@mui/material/CssBaseline";
import * as React from "react";
import BrandBar from "../components/BrandBar/BrandBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.Fragment>
      <CssBaseline />
      <html lang="en">
        <body>
          <BrandBar />
          {children}
        </body>
      </html>
    </React.Fragment>
  );
}
